language: cpp
before_script:
  - sudo apt-get install libboost-test-dev -y
  # sudo apt-get install libboost-log-dev -y
  # sudo apt-get install libboost-program-options-dev -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install gcc-6 -y
  - sudo apt-get install g++-6 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo apt-get install doxygen -y
  - sudo apt-get install graphviz -y
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
  - doxygen
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ushaj:$BINTRAY_API_KEY "https://api.bintray.com/content/andreyshaj/otuscpp/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ./pages/html
    on:
      branch: master